name: alnur
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  quran: ^1.2.9
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  hexcolor: ^3.0.1
  get_it: ^7.6.7
  flutter_switch: ^0.3.2
  flutter_native_splash: ^2.4.0
  flutter_styled_toast: ^2.2.1
  dio: ^5.4.1
  carousel_slider: ^4.2.1
  equatable:
  dartz:
  internet_connection_checker:
  percent_indicator: ^4.2.3
  salomon_bottom_bar: ^3.3.2
  hive:
  hive_flutter:
  path_provider:
  flutter_screenutil: ^5.9.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.5
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  latlong2: ^0.9.1
  quickalert: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  flutter_qiblah: ^3.0.3
  permission_handler: ^10.2.0



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: QCF_P001
      fonts:
        - asset: assets\fonts\QCF2001.TTF
    - family: uthmanic
      fonts:
        - asset: assets\fonts\UthmanTN1 Ver10.otf

